/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Isaac Kishibe (https://sketchfab.com/Isaac_Kishibe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/james-webb-space-telescope-c5addca8cba14edfa346fda22442bc37
Title: James Webb Space Telescope
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import useScreenSize from '../hooks/useScreenSize'

export default function Jwst(props) {
  const { nodes, materials } = useGLTF('/models/jwst-transformed.glb')
  const size = useScreenSize()

  const modelRef = useRef();

  // Responsive scaling
  const getScale = () => {
    if (size < 480) return [0.35, 0.35, 0.35];   // Very small phones
    if (size < 768) return [0.45, 0.45, 0.45];   // Mobile
    if (size < 1024) return [0.6, 0.6, 0.6];     // Tablet
    return [0.75, 0.75, 0.75]; // Desktop
  };

  // Responsive positioning
  const getBasePosition = () => {
    if (size < 480) return [0.2, -0.3, 0];   // Very small phones
    if (size < 768) return [0.3, -0.35, 0];  // Mobile
    return [0.4, -0.45, 0]; // Desktop
  };

  useFrame((state) => {
    if (modelRef.current) {
      modelRef.current.rotation.y += -0.0025
      const basePos = getBasePosition();
      modelRef.current.position.y = basePos[1] + Math.sin(state.clock.elapsedTime) * 0.09 / 5;
      modelRef.current.position.x = basePos[0] + 1.2 + Math.cos(state.clock.elapsedTime) * 0.09 / 5;
    }
  })

  return (
    <group {...props}
      dispose={null}
      ref={modelRef}
      scale={getScale()}
      position={getBasePosition()}
      >
      
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.black_metal}
        position={[0, 2.365, 0.92]}
        rotation={[-2.873, 0, 0]}
        scale={[-0.032, 0.032, 0.082]}
      />
      <mesh
        name="Object_30"
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.grey_metal}
        position={[0.228, 1.076, 1.493]}
        rotation={[-0.208, -0.063, -3.113]}
        scale={[-0.017, 0.133, 0.179]}
      />
      <mesh
        name="Object_80"
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.material_0}
        position={[0.008, 1.06, -0.888]}
        rotation={[-2.539, 0, 0]}
        scale={[0.018, 0.092, 0.016]}
      />
      <mesh
        name="Object_144"
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.gold_glass}
        position={[0, 1.578, -0.656]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.118}
      />
      <mesh
        name="Object_152"
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials.bat_lp}
        position={[0, -0.46, -0.886]}
        scale={[0.803, 0.358, 0.565]}
      />
      <mesh
        name="Object_154"
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials.plane_low}
        position={[0, 1.577, -0.664]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.718}
      />
      <mesh
        name="Object_158"
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials.solar1}
        position={[0.011, -0.068, -2.812]}
        rotation={[-0.951, 0, 0]}
        scale={[0.543, 0.706, 0.456]}
      />
      <mesh
        name="Object_168"
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials.bat_front}
        position={[0, -0.46, -0.886]}
        scale={[0.803, 0.358, 0.565]}
      />
      <mesh
        name="Object_170"
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials.material}
        scale={[2, 1, 3]}
      />
    </group>
  )
}

useGLTF.preload('/models/jwst-transformed.glb')

