"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MOJackal (https://sketchfab.com/MOJackal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/satellite-51b687b2effb4bd9a1176a8d45b7157d
Title: Satellite
*/

import React, { useRef } from 'react'
import { PerspectiveCamera, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import useScreenSize from '../hooks/useScreenSize'

export default function Satellite(props) {
    const { nodes, materials } = useGLTF('/models/satellite2-transformed.glb')
    const size = useScreenSize()

    const modelRef = useRef()
    const cameraRef = useRef()

    // Responsive scaling and positioning
    const getScale = () => {
        if (size < 480) return [0.2, 0.2, 0.2];  // Very small phones
        if (size < 768) return [0.25, 0.25, 0.25]; // Mobile
        if (size < 1024) return [0.3, 0.3, 0.3];  // Tablet
        return [0.34, 0.34, 0.34]; // Desktop
    };

    const getPosition = () => {
        if (size < 480) return [-8, -8, -5];   // Very small phones
        if (size < 768) return [-10, -10, -6]; // Mobile
        return [-14, -14, -7]; // Desktop
    };

    useFrame((state, delta, xrFrame) => {
        // This function controls satellite movement
        // OPTION 1
        // modelRef.current.position.y = -0.1 / 2 + Math.sin(state.clock.elapsedTime) * 0.1 / 120;
        // modelRef.current.position.x = -0.4 / 2 + Math.cos(state.clock.elapsedTime) * 0.1 / 200;
        // OPTION 2
        modelRef.current.position.y = .2 + Math.sin(state.clock.elapsedTime) * 1.1 / 100;
        modelRef.current.position.x = -0.4 + Math.cos(state.clock.elapsedTime) * 2 / 100;
        modelRef.current.position.z = -7; // Push the satellite further back in the Z-axis

        // Make the background zoom faster by adjusting camera FOV
        if (cameraRef.current) {
            // Increase FOV to zoom in faster
            cameraRef.current.fov = 105 + Math.sin(state.clock.elapsedTime) * .25;
            cameraRef.current.updateProjectionMatrix();
        }
    })

    return (
        <>
            <PerspectiveCamera
                ref={cameraRef}
                makeDefault
                position={[0, 0, 0]} // Set an initial camera position
                fov={750}  // Initial field of view
            />
            <group {...props} dispose={null}    // Makes adjustments to the satellite position
                ref={modelRef}
                position={getPosition()}
                scale={getScale()}
                rotation={[0.10, -0.30, -0.12]}>
                <mesh
                    name="Object_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.PaletteMaterial001}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
            </group>
        </>
    )
}

useGLTF.preload('/models/satellite2-transformed.glb')

