/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function SaturnV(props) {
  const { nodes, materials } = useGLTF('/models/SaturnV-transformed(2).glb')
  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.y += 0.0075
  })

  return (
    <group {...props} dispose={null}
      scale={[.87, .87, .87]}
      position={[0, -2, 0]}
      ref={modelRef}
    >
      <group name="saturnV-transformedglb" position={[-0.014, 0, 0]} scale={0.06}>
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Apollo_Metal}
          position={[0, 99.185, 0]}
        />
        <mesh
          name="Object_10"
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.material_0}
          position={[0, 94.479, 0]}
        />
        <mesh
          name="Object_29"
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.White}
          position={[0, 102.406, 0]}
        />
        <mesh
          name="Object_30"
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.Black}
          position={[0, 102.406, 0]}
        />
        <mesh
          name="Object_110"
          castShadow
          receiveShadow
          geometry={nodes.Object_110.geometry}
          material={materials.Saturn_V_Main}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SaturnV-transformed(2).glb')

