/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import useScreenSize from '../hooks/useScreenSize'

export default function SaturnV(props) {
  const { nodes, materials } = useGLTF('/models/SaturnV-transformed(2).glb')
  const modelRef = useRef();
  const size = useScreenSize();
  
  // Responsive scaling based on screen size
  const getScale = () => {
    if (size < 480) return [0.4, 0.4, 0.4];  // Very small phones
    if (size < 768) return [0.5, 0.5, 0.5];  // Mobile
    if (size < 1024) return [0.65, 0.65, 0.65]; // Tablet
    return [0.75, 0.75, 0.75]; // Desktop - smaller than original
  };

  // Responsive positioning
  const getPosition = () => {
    if (size < 768) return [0, -1, 0]; // Mobile - move up slightly
    return [0, -2, 0]; // Desktop
  };

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.0075
    }
  })

  return (
    <group {...props} dispose={null}
      scale={getScale()}
      position={getPosition()}
      ref={modelRef}
    >
      <group name="saturnV-transformedglb" position={[-0.014, 0, 0]} scale={size < 768 ? 0.04 : 0.05}>
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Apollo_Metal}
          position={[0, 99.185, 0]}
        />
        <mesh
          name="Object_10"
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.material_0}
          position={[0, 94.479, 0]}
        />
        <mesh
          name="Object_29"
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.White}
          position={[0, 102.406, 0]}
        />
        <mesh
          name="Object_30"
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.Black}
          position={[0, 102.406, 0]}
        />
        <mesh
          name="Object_110"
          castShadow
          receiveShadow
          geometry={nodes.Object_110.geometry}
          material={materials.Saturn_V_Main}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SaturnV-transformed(2).glb')

